### PR TITLE
Close event

### PR DESCRIPTION
**Pull request by uwburn**
I have implemented the test case for the close option, it's not exactly how i use it but should suffice, as my original scenario is complex to reproduce without including other dependencies.

### CODE REVIEW

**Comment by sedenardi** [comment]
A couple of notes.

*Code questions*
- What's the purpose of the `goNext()` function? Why not just call `nextStream()` directly? It seems like it's to prevent `nextStream()` from being called twice by the stream. If this is the case, can you explain why this happens?
- From the Node.js docs, it looks like you can call `destroy()` on both `Readable` and `Transform` streams, but while both will emit `error`, only `Transform` emits `close`. Is there a use case for wanting to use this for `Readable` streams too?
- Can you rename the `close` option to something more descriptive? It looks too similar to a stream event type. Maybe `advanceOnClose`? 

*Backwards compatibility*
- Refrain from using `let` and `const` so we can continue to target older versions of node

*Code Style*
- Add brackets around `if`/`else` blocks
- Always use 2 spaces to indent, never tabs

**Comment by uwburn** [comment]
- goNext prevents advancing two times for streams that emits both end and close. E.g. a completed readableFileStream will emit `end` and then it will also emit `close` after a while.
- As far as i understand and experienced `destroy()` emit `error` only if error is passed to `destroy()`, but i worked on `Transform` streams, if close is not emitted on `Readable` streams, then i don't think it's really useful for them.
- Ok for `advanceOnClose`.

As for `let` and `const`, i think there was at least one already used in the tests, i also tried to avoid them but i i will double check for it. Same for the code style, i worked outside the IDE to avoid reformats, but some tab might have slipped in, bracketless `if / else` are just my bad habit :).

**Comment by sedenardi** [comment]
No worries. Everything else looks good. I'll go ahead and merge it in later today and cleanup the tabs/spaces stuff. I'll let you know when it's all done and push a new version to `npm`.

**Comment by sedenardi** [comment]
Merged and published to `npm` as version `0.2.0`. 

Note, I've renamed the `close` option to `advanceOnClose` to make it a bit more descriptive.

**Pull request merged**
